version: '3.8'

services:
  backend:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --reload liangziduidie.wsgi:application
    volumes:
      - .:/home/liangziduidie_demo
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_MYSQL_DATABASE=liangziduidie
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=root
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_REDIS_URL=redis:6379

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
