# Generated by Django 5.2.4 on 2025-07-26 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BashModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update_at')),
            ],
        ),
        migrations.CreateModel(
            name='PostReadCount',
            fields=[
                ('bashmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.bashmodel')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('read_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            bases=('blog.bashmodel',),
        ),
    ]
