# Generated by Django 5.2.4 on 2025-07-26 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bashmodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='bashmodel',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='postreadcount',
            name='post_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postreadcount',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='postreadcount',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='用户名'),
        ),
    ]
