# Generated by Django 5.2.4 on 2025-07-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bashmodel_create_at_alter_bashmodel_update_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('bashmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.bashmodel')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            bases=('blog.bashmodel',),
        ),
        migrations.AlterField(
            model_name='postreadcount',
            name='post_id',
            field=models.IntegerField(verbose_name='文章ID'),
        ),
    ]
