# Generated by Django 5.2.4 on 2025-07-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bashmodel_create_at_alter_bashmodel_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreadcount',
            name='post_id',
            field=models.IntegerField(default=0, verbose_name='文章id'),
        ),
    ]
